### ISSUE TITLE
optionally disable the opsman vm creation?

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/terraforming-gcp#101]
Hi! We (platform-automation) are using terraforming-* to pave our infrastructure to test our automation tooling. In particular, our tooling manages the Ops Manager VM itself.

We'd like to make creating the main Ops Manager instance optional across all the terraforming-* repos. We're bringing it up here because currently, we are using `override.tf` to disable the creating of the VM. As of the latest release, we can't do that anymore, because the OpsMan instance is in a module now. (We appreciate the irony that it was merging our PR that created this problem.) It would be nice if we can just set a value in the vars.tf to disable it.

An implementation note: we still need all the other variables associated with the Ops Man VM to be created - for instance, IPs. This means that they'll need to be structured such that the OM instance depends on them, rather than the other way around.

**Comment by nmahoney-pivotal** [comment]
@fredwangwang This work was completed in [this](https://github.com/pivotal-cf/terraforming-gcp/commit/f4d9fd8568298852aa820908aac127cd8d80ad64) commit (and the 3 commits before it). Please reopen this issue if we missed something.
