### ISSUE TITLE
terraforming-gcp/modules/external_database/cloud_sql.tf cannot parse "false" as an integer

### ISSUE THREAD

**Issue by fenixam** [pivotal-cf/terraforming-gcp#110]
should be count = "${var.create ? 1 : 0}"

**Comment by cdutra** [comment]
Hi @fenixam, thanks for bringing this to our attention.
We don't get this error. Can you try with the latest version of terraform and providers, please?
Will close, if you keep getting the error feel free to reopen.

Thanks!
