### ISSUE TITLE
Consider replacing `pcf.<domain>` with `pas.*` and `pks.*`

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/terraforming-gcp#116]
[The README notes this spins up opsmgr's DNS at `pcf.$env_name.$dns_suffix:`](https://github.com/pivotal-cf/terraforming-gcp#dns-records). Because PAS and PKS require (recommend) separate opsmgrs, perhaps it would be preferable to set up separate DNS entries for each? And in doing so, `pcf.*` could become `pas.*`, and the PKS opsmgr would be located at `pks.*`. 

Just a suggestion; could be naive. (Plus who knows, maybe someday PAS and PKS will be colocated on the same opsmgr, and then this would have to be reverted?)

**Comment by zachgersh** [comment]
@aegershman - where did you see a note that you should deploy pks / pas to separate ops managers? I believe the ultimate thought is that customers would have both running on the same ops manager and serving separate workloads.

We'd prefer to leave this for now. Doesn't seem like a problem at present.

**Comment by aegershman** [comment]
[Sure thing, this is from the PKS documentation](https://docs.pivotal.io/runtimes/pks/1-3/pas-and-pks.html#security)

>Ops Manager deploys the PAS and PKS runtime platforms using BOSH. For security reasons, Pivotal does not recommend installing PAS and PKS on the same Ops Manager instance. For even stronger security, Pivotal recommends deploying each Ops Manager instance using a unique cloud provider account.

**Comment by haydonryan** [comment]
From a Field team perspective, we're doing that as well @zachgersh - separate OM for pks.
