### ISSUE TITLE
Document tested terraform version

### ISSUE THREAD

**Issue by kirederik** [pivotal-cf/terraforming-gcp#19]
Would be good to have in the README/Release notes the version of terraform that the scripts were tested with, as terraform can ([and will](https://github.com/hashicorp/terraform/issues/11556)) introduce breaking changes that can be quite destructive.

For example, running v0.6.0 with terraform v0.8.5 wiped out all of our IAM configuration.

**Comment by zachgersh** [comment]
@kirederik great idea - we'll make sure to add a bigger note at the top about this.
