### ISSUE TITLE
Can't SSH into bosh director.

### ISSUE THREAD

**Issue by dbbaskette** [pivotal-cf/terraforming-gcp#22]
Successfully deployed the cluster and have everything up and running on GCP.   I can get into Opsmanager fine, and I can target the bosh director fine, but I cannot seem to figure out how to ssh into the director itself.   I can ping the instance, I can telnet to port 22.  I have tried ubuntu, my login, root, vcap...nothing seems to work.

**Comment by cholick** [comment]
@dbbaskette do you happen to have the commits or PR handy that implemented this?
