### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/terraforming-gcp#32]
Hello,

Is there a timeline for when the next release will be cut? Toolsmiths have been waiting to use our PR https://github.com/pivotal-cf/terraforming-gcp/pull/26  ,  and we've just had another deploy failure because of left-over storage buckets.

Thanks!
Mike J

**Comment by ryanmoran** [comment]
@mjj209 we need to finish this work first: https://www.pivotaltracker.com/story/show/150416862
