### ISSUE TITLE
feature request:  add an on-demand subnet

### ISSUE THREAD

**Issue by eitansuez** [pivotal-cf/terraforming-gcp#37]
rationale: many of the tiles these days require an on demand services subnet be specified.  it'd be convenience if networks.tf automatically created it.  thanks.

**Comment by matthewfischer** [comment]
Since there's only service network anymore I think we can close this?

**Comment by eitansuez** [comment]
sure.  i haven't kept up with changes in pcf.  is an on-demand subnet no longer required to install on-demand services?

**Comment by matthewfischer** [comment]
Yes since 2.? (I think 2.1?) they've collapsed the services and on-demand services networks into 1 network.

**Comment by matthewfischer** [comment]
@cdutra  can we close please
