### ISSUE TITLE
Handling GCP network flakes

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/terraforming-gcp#38]
The Toolsmiths have seen an issue with about 2% (2 out of 100) of our deploys related to network flakes on GCP. The terraform commands run on a GCP Concourse worker, so we're in the same region.

 We issue a command to create an object, then we get 'read: connection reset by peer'. Terraform fails, and then we do a terraform refresh before we try again. The subsequent terraform does not work, as there's a collision in names with the object that already exists. I can provide the full logs for the most recent occurrence.

Currently, we've found that doing a terraform destroy, and then a terraform apply will correctly delete & recreate the objects. We're planning to automate this in our app, with retries in the concourse pipeline, but it would be great if this functionality could get pushed into this repo so that everyone could get higher success rates on terraforming, even with IaaS instability.

**Comment by evanfarrar** [comment]
I guess I wonder where you think we could apply a fix? I am not aware of a feature to add retry logic in terraform, but certainly the provider plugin opens a connection to the GCP api, perhaps it could do better to keep that active or come with embedded awareness of the published limits of connection re-use from GCP's api docs.

1. Is it possible to tell any trends about which object fails? Perhaps that could scope our fix to attempting to normalize how we generate those objects or to the 
2. what version of terraform / the gcp provider do you have? I think it can be found in terraforming-gcp/.terraform/providers/gcp/provider-lock.json or something similar.

**Comment by genevieve** [comment]
Going to close this out due to inactivity.
