### ISSUE TITLE
Feature Request: Make creating a service account optional

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/terraforming-gcp#39]
Hello,

This repo creates a service account which Toolsmiths do not use. We think it could be better to have a flag that will cause it to not create the service account.

This affects us because teams will often not provision their JSON Keys with the proper permissions and our concourse pipeline will fail when terraform tries to create the SA.

Do you think the right thing to do is make the creation of the service account optional?

Thanks,
Mike J
PM@Toolsmiths

**Comment by genevievelesperance** [comment]
Hey @mjj209. Are you referring to the Ops Manager service account? We attach this account to the Ops Manager instance so it does not use the default GCE account and has limited service scopes.
Is there a way we could make it more clear that IAM needs to be enabled for the account they use?

**Comment by mjj209** [comment]
Hi @genevievelesperance  Yes, I'm referring to the "<env> Ops Manager VM Service Account". We request a 'Project - Editor' key, and then use the GCE account for deploying BOSH/ERT. I know we're supposed to use the other key, but we're optimizing for repeatability & success rates right now.

Our main problem is that some customers use a GCE key that does not have 'Project - Editor' permissions, and the majority of these "Permissions" errors are from creating the Service Account key. I would say that your documentation is clear for the requirements, although I'm not 100% convinced that 'Project - Owner' privs are required. We've just updated our home-page that now has the permissions requirement as the 1st line in red text.

It seems that it may be best to leave the current configuration as-is. We may update our app so that it checks for the required permissions during the validate step. This is just a really hard thing to validate, and we probably won't do it until we have many more failures of this type.

I would be happy to show you & your team how our app is consuming the terraforming-gcp repo, our failure categories, and how we've been doing 400+ deploys per month using it.

Cheers,
Mike
