### ISSUE TITLE
Secrets like passwords should be marked as `sensitive` in output

### ISSUE THREAD

**Issue by ljfranklin** [pivotal-cf/terraforming-gcp#40]
Right now secrets like private keys and passwords are printed to stdout in plain text when running `terraform apply` or via automation like the Concourse [terraform-resource](https://github.com/ljfranklin/terraform-resource). To avoid this, Terraform allows you to mark certain output fields as [sensitive](https://www.terraform.io/docs/configuration/outputs.html#sensitive) to make sure they get redacted when printing debug info to stdout. Could y'all mark some of the outputs like `ops_manager_ssh_private_key` as `sensitive` to cut down on exposure of secrets?

**Comment by genevievelesperance** [comment]
Hey @ljfranklin! Added sensitive to passwords and keys. Cut v0.13.0. Thanks!

**Comment by ljfranklin** [comment]
So fast, thanks!
