### ISSUE TITLE
Inconsistently Named SSL Private Key Variable Name

### ISSUE THREAD

**Issue by davewalter** [pivotal-cf/terraforming-gcp#41]
Hi,

We noticed that you had updated the AWS templates to accept a user-provided SSL cert/key instead of generating a self-signed cert, but the variable for the private key doesn't match the one in this repo. It would be nice if there was a common interface for people consuming all of the templates so that they don't have to think about which IaaS they are working with and what the input variables are called.

Thanks!
@davewalter && @ljfranklin

**Comment by genevievelesperance** [comment]
In the latest release!
