### ISSUE TITLE
EU buckets

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/terraforming-gcp#44]
v0.14.0
storage.tf does not have 'location' so buckets ends up in US
It should be configurable to EU or Asia
https://www.terraform.io/docs/providers/google/r/storage_bucket.html
<img width="373" alt="screen shot 2017-12-08 at 00 58 37" src="https://user-images.githubusercontent.com/5575656/33744723-f81a779e-dbb2-11e7-8b58-4bb9c1198166.png">

**Comment by genevievelesperance** [comment]
Thanks for opening this! 

We've made the buckets location configurable and will cut a release.
