### ISSUE TITLE
management network /26

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/terraforming-gcp#47]
The variable.tf defaults to a /24 for management
the Pivotal docs defaults to a /26
https://github.com/pivotal-cf/terraforming-gcp/blob/master/variables.tf#L21

**Comment by genevieve** [comment]
The networks are different in a few ways.

The management/infrastructure network in 
**terraform**: `10.0.0.0/24`
**pivotal docs**: `192.168.101.0/26`

The pas/ert network in
**terraform**: `10.0.4.0/24`
**pivotal docs**: `192.168.16.0/22`

The services network in
**terraform**: `10.0.8.0/24`
**pivotal docs**: `192.168.20.0/22`

[Docs](https://docs.pivotal.io/pivotalcf/2-0/customizing/gcp-prepare-env.html#create_network)

We will be meeting today to decide how to align the docs and the terraform templates on the network range recommendations.

cc @evanfarrar
