### ISSUE TITLE
PKS

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/terraforming-gcp#48]
I have forked your repo and added what I needed for
- PKS network
- bastion machine
- terraforming the LB for an on demand K8 cluster after PKS creation

in this repo in this branch:
https://github.com/avasseur-pivotal/terraforming-gcp/tree/avasseur-pks

I am wondering if some of it could be merged

**Comment by genevievelesperance** [comment]
Thanks to @vchrisb, we merged PKS support. Does this module support the features you need? https://github.com/pivotal-cf/terraforming-gcp/pull/55

**Comment by genevievelesperance** [comment]
Going to close this issue and you can open a PR with any modifications to the PKS module! 

Thanks.
