### ISSUE TITLE
default networks differ from Pivotal docs

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/terraforming-gcp#49]
Pivotal docs has examples with 192.168...
You are using 10.0...
I think it would be best to sync (may be change the docs?)
https://docs.pivotal.io/pivotalcf/2-0/customizing/gcp-om-config-terraform.html#network

**Comment by cdutra** [comment]
@avasseur-pivotal This is the [Reference Architecture docs](https://docs.pivotal.io/pivotalcf/2-3/refarch/).
