### ISSUE TITLE
terraform failure if not using isolation_segment

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/terraforming-gcp#51]
The recent change to `output` for the isolation segment triggers an error, if `isolation_segment` is set to false:

```
Error: Error running plan: 1 error(s) occurred:

* module.isolation_segment.output.domain: Resource 'google_dns_record_set.wildcard-iso-dns' not found for variable 'google_dns_record_set.wildcard-iso-dns.name'
```

https://github.com/pivotal-cf/terraforming-gcp/blob/4b9a560a3a44a4bd76b53a235472ef7759402f6e/isolation_segment/outputs.tf#L16

**Comment by genevievelesperance** [comment]
This will be in the next release. Thanks!

**Comment by genevievelesperance** [comment]
This is in release `v0.18.0`
