### ISSUE TITLE
SQL Database Instance does not have attribute `ip_address.0.ip_address`

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/terraforming-gcp#53]
referring Issue, already created by @genevievelesperance, with Terraform >1.11 and output of `ip_address.0.ip_address` of the `google_sql_database_instance`

https://github.com/terraform-providers/terraform-provider-google/issues/912

**Comment by genevievelesperance** [comment]
Hi @vchrisb. We are waiting on a resolution to the issue I opened before making a change to the external database module. Temporarily we can recommend setting `TF_WARN_OUTPUT_ERRORS=1`, but we are looking for a better solution.

**Comment by genevieve** [comment]
We have a PR open here for this bug: https://github.com/terraform-providers/terraform-provider-google/pull/1050

**Comment by genevieve** [comment]
We have decided to make the sql db instance by default (instead of optionally) as there has been no response in regards to the issue or pr for fixing this in terraform. It should be in the next release and we will update the docs!

**Comment by mjj209** [comment]
really excited to start using the CloudSQL DB, as it should reduce costs by about $4/day/PCF. Toolsmiths have had this story in our icebox for a while, and should be easy for us to switch once we upgrade terraform: https://www.pivotaltracker.com/story/show/153573039
