### ISSUE TITLE
google_compute_instance.ops-manager: [ERR] Error decoding timeout: Timeout Key (create) is not supported

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/terraforming-gcp#54]
The recent commit did replace `create_timeout` by a timeout block, but this raises an error.
```
google_compute_instance.ops-manager: [ERR] Error decoding timeout: Timeout Key (create) is not supported
```

According to the documentation only `create_timeout` is supported:
https://www.terraform.io/docs/providers/google/r/compute_instance.html#create_timeout

**Comment by genevievelesperance** [comment]
You can bump your terraform version with `brew upgrade terraform`.

**Comment by genevievelesperance** [comment]
[create_timeout](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance.go#L552-L557) is deprecated.

If you upgrade your version of terraform, it will pull the gcp provider plugin that supports the new [timeout block](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance.go#L36-L40).

**Comment by vchrisb** [comment]
I think it was a bit quick to adopt this change, as even the documentation is not updated yet. This change was made only 6 days ago and `create_timeout` still works.

I was already running latest terraform version and needed to upgrade the google provider in my terraforming-gcp folder.

**Comment by vchrisb** [comment]
needs `terraform-provider-google` >= `1.5.0`

**Comment by genevievelesperance** [comment]
Thats a good point. I'll add the requirement to the release notes. Thank you!
