### ISSUE TITLE
pks got created with incorrect certs

### ISSUE THREAD

**Issue by depohmel** [pivotal-cf/terraforming-gcp#64]
after I run pks get-credentials 

```
kubectl get all
Unable to connect to the server: x509: certificate is valid for 10.100.200.1, not my-cluster
```

pks version: 1.0.0 and 1.0.1
internal cluster ip: 10.0.0.11
external cluster ip: 35.197.22.74

**Comment by genevieve** [comment]
@vchrisb Have you seen this error before with the the pks module?

**Comment by vchrisb** [comment]
Hi @depohmel 
This repo is not involved in the path to provide TLS termination for the k8s clusters. We deploy a loadbalancer for the PKS api.
For now, we only open port `8443` to all nodes that have the tag `master`, to allow access to the K8s API. 
K8s clusters, and therefore also the certificates, are created by the PKS API on demand using https://github.com/cloudfoundry-incubator/kubo-deployment.
Currently the creation of a new k8s cluster, via PKS api/BOSH, does not configure a GCP Loadbalancer on demand for the master node.

**Comment by depohmel** [comment]
Hi @vchrisb, thanks for the response. I wasn't sure where to submit this issues (i didn't any repo with a name like pks ) so I  post it here.
Yes, it's not a terraform issue.  Let me submit this one to https://github.com/cloudfoundry-incubator/kubo-deployment 

also to access master I just opened access to master vm directly. which is ok for my testing purposes.

**Comment by genevieve** [comment]
Thanks Chris!
