### ISSUE TITLE
Possible delay required after external database creation

### ISSUE THREAD

**Issue by jasonbisson** [pivotal-cf/terraforming-gcp#65]
I've seen this error a couple of times which is resolved by rerunning apply with no issue.

Error: Error applying plan:
1 error(s) occurred:
* google_sql_user.pas: 1 error(s) occurred:
* google_sql_user.pas: Error reading SQL User "xxxxxxx" in instance "xxxx-xxxx": googleapi: Error 503: Service temporarily unavailable., serverException

**Comment by genevieve** [comment]
This is more of an issue with google cloud sql. There is an issue open here: https://github.com/terraform-providers/terraform-provider-google/issues/1138#issuecomment-371636390 and the terraform google provider maintainers have raised this with the correct google team.
