### ISSUE TITLE
Possible PR: Allow `internetless: true` input option

### ISSUE THREAD

**Issue by michelleheh** [pivotal-cf/terraforming-gcp#69]
We're setting up a testing pipeline to check that our deployments work in an internetless environment. This means all traffic going outside the 10.* network is denied. We can either create a terraform override file just for us, or if you thought this was generally useful we could PR to this repo as an optional input variable. WDYT?

**Comment by jasonbisson** [comment]
I think this would be a great option because most enterprises want to limit the exposure of public internet access.

**Comment by rowanjacobs** [comment]
If you could write that PR, we'd be willing to merge it.
