### ISSUE TITLE
make certificates replacable

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/terraforming-gcp#76]
Update a certificate for the GCP load balancer in place is not possible.
It is necessary to first create a new one before destroying the old one.

This is supported by [google_compute_ssl_certificate](https://www.terraform.io/docs/providers/google/r/compute_ssl_certificate.html) by using a `name_prefix` and configure `create_before_destroy `

`name = "${var.env_name}-lbcert"` in [router.tf](https://github.com/pivotal-cf/terraforming-gcp/blob/master/router.tf#L81) should be replaced by `name_prefix = "${var.env_name}-lbcert-"`

**Comment by vchrisb** [comment]
I've seen we recently switched from `name_prefix` to `name` because of https://github.com/terraform-providers/terraform-provider-google/issues/1054.
So the fix would be to keep `name` but add a random string at the end:
```
resource "random_id" "cert" {
  byte_length = 8
}

resource "google_compute_ssl_certificate" "cert" {
  name        = "${var.env_name}-lbcert-${random_id.cert.dec}"
  description = "user provided ssl private key / ssl certificate pair"
  certificate = "${length(var.ssl_ca_cert) > 0 ? element(concat(tls_locally_signed_cert.ssl_cert.*.cert_pem, list("")), 0) : var.ssl_cert}"
  private_key = "${length(var.ssl_ca_cert) > 0 ? element(concat(tls_private_key.ssl_private_key.*.private_key_pem, list("")), 0) : var.ssl_private_key}"

  lifecycle = {
    create_before_destroy = true
  }
}

I'll try it and do a pull request...

**Comment by nmahoney-pivotal** [comment]
> I'll try it and do a pull request...

Thanks @vchrisb! That's super helpful.

**Comment by vchrisb** [comment]
While digging further into it and struggling with getting `keepers` right, I saw that the deprecation of `name_prefix` was actually reverted, exactly because of this issue
https://github.com/terraform-providers/terraform-provider-google/issues/1326 
https://github.com/terraform-providers/terraform-provider-google/pull/1622 

I'm going to update the pull request to just revert back to use `name_prefix`
