### ISSUE TITLE
SSH access to Director VM

### ISSUE THREAD

**Issue by masalinas** [pivotal-cf/terraforming-gcp#80]
I deployed Pivotal PAS Small Footprint Elastic Runtime using previously the ofitial terraform templates, my question is how can I ssh to Terraform?

From my Personal PC the 22 port is closed.
From OPs Manager the port 22 is open, I tryed use the  vcap with the password from credentials, but the vcap ssh is unactive, so I supouse need the private Key to access, but where is this private Key?, terraform output variables created for me? 

Regards

**Comment by cwlbraa** [comment]
user is ubuntu, your ssh key is the private key provided by the terraform output "ops_manager_ssh_private_key"
