### ISSUE TITLE
`google_service_account.opsman_service_account` should be an output

### ISSUE THREAD

**Issue by anEXPer** [pivotal-cf/terraforming-gcp#81]
In order to configure Ops Man on GCP with `om`, it's necessary to use the service account name terraform creates for the OM VM. (In the GUI, this isn't necessary, as Ops Manager detects the service account itself, but that's a whole other issue.)

google_service_account.opsman_service_account should be an output - it means you don't have to provide an auth_json when configuring the director, which is one less secret getting passed around in files.

**Comment by cdutra** [comment]
Hi @anEXPer, we added to Ops Manager service account key as an output of our terraforming-gcp for pas, pks and control-plane. Thanks for filing this issue!

Changes in the following commit: https://github.com/pivotal-cf/terraforming-gcp/commit/7e398dd69db6362bf3568cb60aad9fb432c09bb9

It went through in our pipeline and we have draft release.
