### ISSUE TITLE
Resource 'google_sql_database_instance.master' not found for variable

### ISSUE THREAD

**Issue by jasonbisson** [pivotal-cf/terraforming-gcp#84]
I tried deploying today and this error I got after the latest commit.

Error: Error running plan: 1 error(s) occurred:

module.external_database.output.pas_sql_cert: Resource 'google_sql_database_instance.master' not found for variable 'google_sql_database_instance.master.server_ca_cert.0.cert'

**Comment by genevieve** [comment]
@evanfarrar @Pivotal-Jayson-Hairston Could we revert the last commit with the PR that caused this bug until it's fixed so we can make PRs against a green master branch?

**Comment by genevieve** [comment]
The output error has been reverted.
