### ISSUE TITLE
InstanceGroup alreadyExists Failure

### ISSUE THREAD

**Issue by jyidiego** [pivotal-cf/terraforming-gcp#9]
Consistently get the following:

Error applying plan:

2 error(s) occurred:

* google_compute_instance_group.httplb.1: Error creating InstanceGroup: googleapi: Error 409: The resource 'projects/fe-jyi/zones/us-east1-d/instanceGroups/pcflab-httpslb-us-east1-d' already exists, alreadyExists
* google_compute_instance_group.httplb.2: Error creating InstanceGroup: googleapi: Error 409: The resource 'projects/fe-jyi/zones/us-east1-d/instanceGroups/pcflab-httpslb-us-east1-d' already exists, alreadyExists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Followed the instructions from the README but still seemed to get this error. Even tried to eliminate parallelism. Running this on MacOSX.

**Comment by jyidiego** [comment]
I figured out what is going on. So I was using a single AZ because I was intending to deploy a small footprint for a lab. Apparently the router.tf links the instance_group for exactly 3 AZs. This terraform configuration would than only work for exactly three AZs no more no less.

**Comment by ryanmoran** [comment]
@jyidiego we've had an outstanding story to fix this for a while. It is at the top of our backlog: https://www.pivotaltracker.com/story/show/132717937

I will get https://github.com/pivotal-cf/terraforming-gcp/pull/10 merged in the meantime.
